//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.FiksProtokollValidator.WebAPI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestMessageTypes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestMessageTypes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KS.FiksProtokollValidator.WebAPI.Resources.RequestMessageTypes", typeof(RequestMessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ArkivmeldingV1 {
            get {
                return ResourceManager.GetString("ArkivmeldingV1", resourceCulture);
            }
        }
        
        public static string OppdaterSaksmappeV1 {
            get {
                return ResourceManager.GetString("OppdaterSaksmappeV1", resourceCulture);
            }
        }
        
        public static string SoekV1 {
            get {
                return ResourceManager.GetString("SoekV1", resourceCulture);
            }
        }
        
        public static string SendVedtakFraUtvalgV1 {
            get {
                return ResourceManager.GetString("SendVedtakFraUtvalgV1", resourceCulture);
            }
        }
        
        public static string FinnPlanerForMatrikkelEnhetV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForMatrikkelEnhetV2", resourceCulture);
            }
        }
        
        public static string RegistrerDispensasjonForPlanV2 {
            get {
                return ResourceManager.GetString("RegistrerDispensasjonForPlanV2", resourceCulture);
            }
        }
        
        public static string RegistrerPlanavgrensingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanavgrensingV2", resourceCulture);
            }
        }
        
        public static string FinnPlanerV2 {
            get {
                return ResourceManager.GetString("FinnPlanerV2", resourceCulture);
            }
        }
        
        public static string FinnDispensasjonerV2 {
            get {
                return ResourceManager.GetString("FinnDispensasjonerV2", resourceCulture);
            }
        }
        
        public static string OpprettArealplanV2 {
            get {
                return ResourceManager.GetString("OpprettArealplanV2", resourceCulture);
            }
        }
        
        public static string RegistrerPlanbehandlingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanbehandlingV2", resourceCulture);
            }
        }
        
        public static string OppdaterArealplanV2 {
            get {
                return ResourceManager.GetString("OppdaterArealplanV2", resourceCulture);
            }
        }
    }
}
