//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.FiksProtokollValidator.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestMessageTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestMessageTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS.FiksProtokollValidator.WebAPI.Resources.RequestMessageTypes", typeof(RequestMessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finndispensasjoner.v2.
        /// </summary>
        public static string FinnDispensasjonerV2 {
            get {
                return ResourceManager.GetString("FinnDispensasjonerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplandokumenter.v2.
        /// </summary>
        public static string FinnPlandokumenterV2 {
            get {
                return ResourceManager.GetString("FinnPlandokumenterV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplanerformatrikkelenhet.v2.
        /// </summary>
        public static string FinnPlanerForMatrikkelEnhetV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForMatrikkelEnhetV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplanerforområde.v2.
        /// </summary>
        public static string FinnPlanerForOmrådeV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForOmrådeV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplaner.v2.
        /// </summary>
        public static string FinnPlanerV2 {
            get {
                return ResourceManager.GetString("FinnPlanerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentaktører.v2.
        /// </summary>
        public static string HentAktørerV2 {
            get {
                return ResourceManager.GetString("HentAktørerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentbboxforplan.v2.
        /// </summary>
        public static string HentBboxV2 {
            get {
                return ResourceManager.GetString("HentBboxV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentgjeldendeplanbestemmelser.v2.
        /// </summary>
        public static string HentGjeldendePlanbestemmelserV2 {
            get {
                return ResourceManager.GetString("HentGjeldendePlanbestemmelserV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentkodeliste.v2.
        /// </summary>
        public static string HentKodelisteV2 {
            get {
                return ResourceManager.GetString("HentKodelisteV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentplanfil.v2.
        /// </summary>
        public static string HentPlanfilV2 {
            get {
                return ResourceManager.GetString("HentPlanfilV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentplanområder.v2.
        /// </summary>
        public static string HentPlanområderV2 {
            get {
                return ResourceManager.GetString("HentPlanområderV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.hentrelaterteplaner.v2.
        /// </summary>
        public static string HentRelatertePlanerV2 {
            get {
                return ResourceManager.GetString("HentRelatertePlanerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.oppdaterarealplan.v2.
        /// </summary>
        public static string OppdaterArealplanV2 {
            get {
                return ResourceManager.GetString("OppdaterArealplanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.oppdaterdispensasjon.v2.
        /// </summary>
        public static string OppdaterDispensasjonV2 {
            get {
                return ResourceManager.GetString("OppdaterDispensasjonV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.opprettarealplan.v2.
        /// </summary>
        public static string OpprettArealplanV2 {
            get {
                return ResourceManager.GetString("OpprettArealplanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerdispensasjonplan.v2.
        /// </summary>
        public static string RegistrerDispensasjonForPlanV2 {
            get {
                return ResourceManager.GetString("RegistrerDispensasjonForPlanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrermidlertidigforbudmottiltak.v2.
        /// </summary>
        public static string RegistrerMidlertidigForbudMotTiltakV2 {
            get {
                return ResourceManager.GetString("RegistrerMidlertidigForbudMotTiltakV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerplanavgrensning.v2.
        /// </summary>
        public static string RegistrerPlanavgrensingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanavgrensingV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerplanbehandling.v2.
        /// </summary>
        public static string RegistrerPlanbehandlingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanbehandlingV2", resourceCulture);
            }
        }
    }
}
