//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.FiksProtokollValidator.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestMessageTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestMessageTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS.FiksProtokollValidator.WebAPI.Resources.RequestMessageTypes", typeof(RequestMessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.arkivintegrasjon.oppdatering.basis.arkivmelding.v1.
        /// </summary>
        public static string ArkivmeldingV1 {
            get {
                return ResourceManager.GetString("ArkivmeldingV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finndispensasjoner.v2.
        /// </summary>
        public static string FinnDispensasjonerV2 {
            get {
                return ResourceManager.GetString("FinnDispensasjonerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplanerformatrikkelenhet.v2.
        /// </summary>
        public static string FinnPlanerForMatrikkelEnhetV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForMatrikkelEnhetV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.finnplaner.v2.
        /// </summary>
        public static string FinnPlanerV2 {
            get {
                return ResourceManager.GetString("FinnPlanerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.klient.hentmøteplan.v1.
        /// </summary>
        public static string HentMoteplanV1 {
            get {
                return ResourceManager.GetString("HentMoteplanV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.klient.hentutvalg.v1.
        /// </summary>
        public static string HentUtvalgV1 {
            get {
                return ResourceManager.GetString("HentUtvalgV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.oppdaterarealplan.v2.
        /// </summary>
        public static string OppdaterArealplanV2 {
            get {
                return ResourceManager.GetString("OppdaterArealplanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.arkivintegrasjon.oppdatering.basis.oppdatersaksmappe.v1.
        /// </summary>
        public static string OppdaterSaksmappeV1 {
            get {
                return ResourceManager.GetString("OppdaterSaksmappeV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.opprettarealplan.v2.
        /// </summary>
        public static string OpprettArealplanV2 {
            get {
                return ResourceManager.GetString("OpprettArealplanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerdispensasjonplan.v2.
        /// </summary>
        public static string RegistrerDispensasjonForPlanV2 {
            get {
                return ResourceManager.GetString("RegistrerDispensasjonForPlanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerplanavgrensning.v2.
        /// </summary>
        public static string RegistrerPlanavgrensingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanavgrensingV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.registrerplanbehandling.v2.
        /// </summary>
        public static string RegistrerPlanbehandlingV2 {
            get {
                return ResourceManager.GetString("RegistrerPlanbehandlingV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.klient.senddelegertvedtak.v1.
        /// </summary>
        public static string SendDelegertVedtakV1 {
            get {
                return ResourceManager.GetString("SendDelegertVedtakV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.klient.sendorienteringssak.v1.
        /// </summary>
        public static string SendOrienteringssakV1 {
            get {
                return ResourceManager.GetString("SendOrienteringssakV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.klient.sendutvalgssak.v1.
        /// </summary>
        public static string SendUtvalgV1 {
            get {
                return ResourceManager.GetString("SendUtvalgV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.politisk.behandling.tjener.sendvedtakfrautvalg.v1.
        /// </summary>
        public static string SendVedtakFraUtvalgV1 {
            get {
                return ResourceManager.GetString("SendVedtakFraUtvalgV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.arkivintegrasjon.innsyn.sok.v1.
        /// </summary>
        public static string SoekV1 {
            get {
                return ResourceManager.GetString("SoekV1", resourceCulture);
            }
        }
    }
}
