//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.FiksProtokollValidator.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessageTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessageTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS.FiksProtokollValidator.WebAPI.Resources.ResponseMessageTypes", typeof(ResponseMessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.aktører.v2.
        /// </summary>
        public static string AktørerV2 {
            get {
                return ResourceManager.GetString("AktørerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.bbox.v2.
        /// </summary>
        public static string BboxV2 {
            get {
                return ResourceManager.GetString("BboxV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.arkivintegrasjon.feil.v1.
        /// </summary>
        public static string FeilV1 {
            get {
                return ResourceManager.GetString("FeilV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.dispensasjonerforsøk.v2.
        /// </summary>
        public static string FinnDispensasjonerForSøkV2 {
            get {
                return ResourceManager.GetString("FinnDispensasjonerForSøkV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.plandokumenter.v2.
        /// </summary>
        public static string FinnPlandokumenterV2 {
            get {
                return ResourceManager.GetString("FinnPlandokumenterV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.planerformatrikkelenhet.v2.
        /// </summary>
        public static string FinnPlanerForMatrikkelenhetV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForMatrikkelenhetV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.planerforområde.v2.
        /// </summary>
        public static string FinnPlanerForOmrådeV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForOmrådeV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.planerforsøk.v2.
        /// </summary>
        public static string FinnPlanerV2 {
            get {
                return ResourceManager.GetString("FinnPlanerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.gjeldendeplanbestemmelser.v2.
        /// </summary>
        public static string GjeldendePlanbestemmelserV2 {
            get {
                return ResourceManager.GetString("GjeldendePlanbestemmelserV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.kodeliste.v2.
        /// </summary>
        public static string KodelisteV2 {
            get {
                return ResourceManager.GetString("KodelisteV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.meldingomplanident.v2.
        /// </summary>
        public static string MeldingOmPlanidentV2 {
            get {
                return ResourceManager.GetString("MeldingOmPlanidentV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.oppdatering.mottatt.v2.
        /// </summary>
        public static string MottattGiPlanV2 {
            get {
                return ResourceManager.GetString("MottattGiPlanV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.plandokumenter.v2.
        /// </summary>
        public static string PlandokumenterV2 {
            get {
                return ResourceManager.GetString("PlandokumenterV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.planfil.v2.
        /// </summary>
        public static string PlanfilV2 {
            get {
                return ResourceManager.GetString("PlanfilV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.planområder.v2.
        /// </summary>
        public static string PlanområderV2 {
            get {
                return ResourceManager.GetString("PlanområderV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.gi.plan.innsyn.relaterteplaner.v2.
        /// </summary>
        public static string RelatertePlanerV2 {
            get {
                return ResourceManager.GetString("RelatertePlanerV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.ks.fiks.kvittering.tidsavbrudd.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
    }
}
