//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.FiksProtokollValidator.WebAPI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessageTypes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessageTypes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KS.FiksProtokollValidator.WebAPI.Resources.ResponseMessageTypes", typeof(ResponseMessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FeilV1 {
            get {
                return ResourceManager.GetString("FeilV1", resourceCulture);
            }
        }
        
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        public static string FinnPlanerForMatrikkelenhetV2 {
            get {
                return ResourceManager.GetString("FinnPlanerForMatrikkelenhetV2", resourceCulture);
            }
        }
        
        public static string MottattGiPlanV2 {
            get {
                return ResourceManager.GetString("MottattGiPlanV2", resourceCulture);
            }
        }
        
        public static string FinnPlanerV2 {
            get {
                return ResourceManager.GetString("FinnPlanerV2", resourceCulture);
            }
        }
        
        public static string FinnDispensasjonerForSøkV2 {
            get {
                return ResourceManager.GetString("FinnDispensasjonerForSøkV2", resourceCulture);
            }
        }
        
        public static string MeldingOmPlanidentV2 {
            get {
                return ResourceManager.GetString("MeldingOmPlanidentV2", resourceCulture);
            }
        }
    }
}
