version: 2
updates:
  - package-ecosystem: docker
    directory: "/api"
    schedule:
      interval: daily
      time: "04:32"
      timezone: Europe/Oslo
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: docker
    directory: "/web-ui"
    schedule:
      interval: daily
      time: "04:32"
      timezone: Europe/Oslo
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: nuget
    directory: "/api"
    schedule:
      interval: daily
      time: "04:32"
      timezone: Europe/Oslo
    open-pull-requests-limit: 15
    groups:
      fiks-deps:
        patterns:
          - "KS.Fiks*"
        update-types:
          - "minor"
          - "patch"
      other-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "KS.Fiks*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/web-ui"
    schedule:
      interval: daily
      time: "04:32"
      timezone: Europe/Oslo
    open-pull-requests-limit: 15
    groups:
      all-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
